name: backoffice
on:
  pull_request:
  push:
    paths:
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      # ----------------
      # Test
      # ----------------
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run:
          docker-compose run app ./gradlew test
      # ----------------
      # Deploy
      # ----------------
      - if: contains('refs/heads/main', github.ref)
        name: Setup fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - if: contains('refs/heads/main', github.ref)
        name: Deploy
        run: flyctl deploy front --config deploy/fly.toml --detach
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
